### ISSUE TITLE
izapple2sdl (Linux) seems to run at full speed only

### ISSUE THREAD

**Issue by hleinders** [ivanizag/izapple2#10]
When started with Merlin8 or APL6502.SIM it seems to run with full speed (about 35 MHz on my Lenovo T440p) always, regardless what's given on the command line (-mhz) or set with F5.

**Comment by ivanizag** [comment]
Are you using Apple6502.DSK from https://macgui.com/downloads/?file_id=8091 ?
I can't repro the issue:
- run  `./izapple2sdl_linux Apple6502.DSK`
- press Ctrl-F5 so see the speed on the terminal.
- with F5, I see how it goes full speed or normal.

Is there something different that I may be missing?

**Comment by hleinders** [comment]
Hi Ivan,
I've got my copy from Asimov some time ago. But, using the newest version I could build now, the behaviour with the same Images is correct now. But using the version your download link points to (izapple2sdl_linux) still shows this bug. Starting APL6502.SIM (on the same image that works with the current version) "races" through the code, no matter what F5 shows. So maybe you only have to update the download link or make a new release. I've just compared the two a minute ago to confirm this with the same disk images.

What happened to the "-mono"-Switch in the current release? I've liked that. :-)

May I suggest some things?

1. for symmetry reasons and the correct "feeling", I would rename -disk and -diskb to -disk1 and -disk2 (On the old Apples there  never was a drive "b", it always was drive "1" and "2" - in fact, an Apple ][+ was my first computer. Yes, I'm that old :-) )
2. "readd" the mono modes, maybe with choices of "green" and "amber"
3. there are som defaults "<default>" in the help page. This can be overridden with something like "`string`" in the flags messages. btw, In my projects I've totally switched from the go flags packages to the viper pflag package as a drop in replacement which allow short and long flags. 
4. What about a configuration file? Maybe viper could help here also (I'm not connected to viper in any way, I just like their packages - https://github.com/spf13/viper). So someone could set personal defaults like machine type, speed, terminal et al.

I really like your keyboard handling! This is the first emulator on linux where I don't have to fiddle with my german keyboard. :-)

**Comment by ivanizag** [comment]
Are you using two disks? I recently fixed an issue with the speed when using two disks. It must be that. Happy to see that it is fixed.

Thanks for the suggestions, I have to fully rewrite the configuration management, it has grown too messy. I want config files and reversing params to specify what is in a particular slot instead of where a card is. Thanks for the tip on viper, it looks promising.

Happy to see that you appreciate the keyboard handling. With my Spanish keyboard I don't have the Y-Z issue but all the symbols are on different places.
