### ISSUE TITLE
Build instruction fails

### ISSUE THREAD

**Issue by hleinders** [ivanizag/izapple2#11]
Maybe github changed something, but the instructions given in the README fail with an error message:

❯ go get github.com/ivanizag/izapple2/izapple2sdl
go get: module github.com/ivanizag/izapple2@upgrade found (v0.0.0-20210306192317-d531a26b2e3e), but does not contain package github.com/ivanizag/izapple2/izapple2sdl

Beside that I really appreciate an Apple Emu in go! :-)

**Comment by ivanizag** [comment]
The README was not updated after a code reorg. It should be fine now.

```
go get github.com/ivanizag/izapple2/frontend/a2sdl
go build github.com/ivanizag/izapple2/frontend/a2sdl
```

Thanks!

**Comment by hleinders** [comment]
Hi Ivan,
I can build a2sdl now (thanks alot!). If a GOPATH exists, only the "go get" is neccessary to build, a "go build" will complain about missing "go.mod". As soon as no GOPATH is found, it will install in the default location "$HOME/go", but also only the "go get" is neccessary, as far as I can see. Maybe I've missed something here, but this results from the fact that you publish it as pkg, not src. But, in case I didn't mention it before: Great work! :-)

BTW: I'm using KDE Neon as distro (which is an ubuntu 20.04 basically) and go 1.16.2.

**Comment by ivanizag** [comment]
Great. I'll review that.

**Comment by ivanizag** [comment]
It should be a bit more clear now.
