### ISSUE TITLE
Mono-Mode disappeared

### ISSUE THREAD

**Issue by hleinders** [ivanizag/izapple2#12]
In former releases, the "-mono" switched worked well for HGR graphics like APL6502.SIM. At the moment, the switch is no longer available and mode switching with F6 shows no effect. Did I miss something? Without the green mono mode, HGR looks ugly. Setting "-rgb=false" also has no effect.

BR, Harald
![snapshot](https://user-images.githubusercontent.com/9589267/111595084-0ca2b500-87cc-11eb-9a71-4492695a0827.png)

**Comment by ivanizag** [comment]
Yes, color is ugly for text. I added back F6 to switch between NTSC color artifacts and green mono.

I'll wait for the command arguments rewrite to add back a way to set that from the command line. I hope that F6 works for you.
