### ISSUE TITLE
Updated macOS build with SDL2 static linked to make izapple2 more accessible 

### ISSUE THREAD

**Issue by samknutson** [ivanizag/izapple2#14]
Installing SDL2 is a non-trivial task for many macOS users who would like to use and help with development or testing of izapple2.  Consider to make an updated build static linking SDL2 so that no external libraries are required to run.   This would reduce the friction that someone who is interested in Apple ][ but is not a highly technical macOS user faces to download and run izapple2.

**Comment by ivanizag** [comment]
Yes, that makes sense. Maybe not to link statically but to create a proper dmg bundle with SDL copied to izapple2.app/Contents/Frameworks/... Would that be a solution?

I don't know much about macOS and won't have access to a Mac until october to test.

**Comment by samknutson** [comment]
Outstanding!  Thank you.
